Paladin/Models/Employment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Paladin.Models
{
    public class Employment
    {
        public int EmploymentId { get; set; }
        public int ApplicantId { get; set; }
        public string EmploymentType { get; set; }
        public string Employer { get; set; }
        public string Position { get; set; }
        public double GrossMonthlyIncome { get; set; }
        public DateTime? StartDate { get; set; }

        public bool IsPrimary { get; set; }
        
        public virtual Applicant Applicant { get; set; }
    }
}

Paladin/ViewModels/Employments.cs
using Paladin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Paladin.ViewModels
{
    public class Employments
    {
        public Employments()
        {
            PrimaryEmployer = new EmploymentVM();
            PreviousEmployer = new EmploymentVM();
        }
        public EmploymentVM PrimaryEmployer { get; set; }
        public EmploymentVM PreviousEmployer { get; set; }
    }
}

Paladin/Controllers/EmploymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Paladin.Models;
using System.Data.Entity;
using Paladin.ViewModels;
using AutoMapper;

namespace Paladin.Controllers
{
    public class EmploymentController : Controller
    {
        private PaladinDbContext _context;

        public EmploymentController()
        {
            _context = new PaladinDbContext();
        }
        // GET: Employment
        public ActionResult EmploymentInfo()
        {
            if (Session["Tracker"] == null)
            {
                return RedirectToAction("ApplicantInfo", "Applicant");
            }
            var tracker = (Guid)Session["Tracker"];

            var employment = new Employments();
            var existingPrimary = _context.Applicants.FirstOrDefault(x => x.ApplicantTracker == tracker).Employment.FirstOrDefault(x => x.IsPrimary);
            if (existingPrimary != null)
            {
                employment.PrimaryEmployer = Mapper.Map<EmploymentVM>(existingPrimary);
            }

            var existingPrevious = _context.Applicants.FirstOrDefault(x => x.ApplicantTracker == tracker).Employment.FirstOrDefault(x => x.IsPrimary == false);
            if (existingPrevious != null)
            {
                employment.PreviousEmployer = Mapper.Map<EmploymentVM>(existingPrevious);
            }
            
            return View(employment);
        }

        [HttpPost]
        public ActionResult EmploymentInfo(Employments vm)
        {
            if (Session["Tracker"] == null)
            {
                return RedirectToAction("ApplicantInfo", "Applicant");
            }
            var tracker = (Guid)Session["Tracker"];

            if (ModelState.IsValid)
            {
                var applicant = _context.Applicants.FirstOrDefault(x => x.ApplicantTracker == tracker);

                var existingEmployment = applicant.Employment.FirstOrDefault(x => x.IsPrimary);
                if (existingEmployment != null)
                {
                    Mapper.Map(vm.PrimaryEmployer, existingEmployment);
                    _context.Entry(existingEmployment).State = EntityState.Modified;
                }
                else
                {
                    var newEmployment = Mapper.Map<Employment>(vm.PrimaryEmployer);
                    newEmployment.IsPrimary = true;
                    applicant.Employment.Add(newEmployment);
                }


                var existingPrevious = applicant.Employment.FirstOrDefault(x => x.IsPrimary == false);
                if (existingPrevious != null)
                {
                    Mapper.Map(vm.PreviousEmployer, existingPrevious);
                    _context.Entry(existingPrevious).State = EntityState.Modified;
                }
                else
                {
                    var newEmployment = Mapper.Map<Employment>(vm.PreviousEmployer);
                    newEmployment.IsPrimary = false;
                    applicant.Employment.Add(newEmployment);
                }

                _context.SaveChanges();
                return RedirectToAction("VehicleInfo", "Vehicle");
            }
            return View();
        }
    }
}

Paladin/Views/Employment/EmploymentInfo.cshtml
@model Paladin.ViewModels.Employments
@{
    ViewBag.Title = "Index";
}
@section ProgressBar{
    @Html.Action("ProgressBar", "Home", new { currentStage = 20 })
}
<div class="col-md-12">
    <h2 class="page-header">What do you do?<small style="margin-left: 25px">Let your hard work pay off!</small></h2>
</div>
<div class="applicant-info">
    @using (Html.BeginForm("EmploymentInfo", "Employment", FormMethod.Post, new { @class = "form" }))
    {
        <div class="col-md-12">
            @Html.ValidationSummary()
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading panel-title">Employment Info</div>
                <div class="panel-body">
                    <div class="form-group">
                        @{
        var employmentTypes = new List<SelectListItem>(){
                                new SelectListItem(){ Text = "Full Time", Value = "1" },
                                new SelectListItem(){ Text = "Part Time", Value = "2" },
                                new SelectListItem(){ Text = "Unemployed", Value = "3" },
                                new SelectListItem(){ Text = "Retired", Value = "4" }
                            };
                        }

                        @Html.LabelFor(x => x.PrimaryEmployer.EmploymentType)
                        @Html.DropDownListFor(x => x.PrimaryEmployer.EmploymentType, employmentTypes, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(x => x.PrimaryEmployer.Employer)
                        @Html.TextBoxFor(x => x.PrimaryEmployer.Employer, new { @class = "form-control required" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(x => x.PrimaryEmployer.Position)
                        @Html.TextBoxFor(x => x.PrimaryEmployer.Position, new { @class = "form-control required" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(x => x.PrimaryEmployer.GrossMonthlyIncome)
                        @Html.TextBoxFor(x => x.PrimaryEmployer.GrossMonthlyIncome, new { @class = "form-control required digits" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(x => x.PrimaryEmployer.StartDate)
                        @Html.TextBoxFor(x => x.PrimaryEmployer.StartDate, new { @Value = Model.PrimaryEmployer.StartDate.HasValue ? Model.PrimaryEmployer.StartDate.Value.ToString("MM/dd/yyyy") : "", @class = "form-control datepicker required" })
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading panel-title">Previous Employment Info</div>
                <div class="panel-body">
                    <div class="form-group">
                        @Html.LabelFor(x => x.PreviousEmployer.EmploymentType)
                        @Html.DropDownListFor(x => x.PreviousEmployer.EmploymentType, employmentTypes, new { @class = "form-control required" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(x => x.PreviousEmployer.Employer)
                        @Html.TextBoxFor(x => x.PreviousEmployer.Employer, new { @class = "form-control required" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(x => x.PreviousEmployer.Position)
                        @Html.TextBoxFor(x => x.PreviousEmployer.Position, new { @class = "form-control required" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(x => x.PreviousEmployer.GrossMonthlyIncome)
                        @Html.TextBoxFor(x => x.PreviousEmployer.GrossMonthlyIncome, new { @class = "form-control required digits" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(x => x.PreviousEmployer.StartDate)
                        @Html.TextBoxFor(x => x.PreviousEmployer.StartDate, new { @Value = Model.PreviousEmployer.StartDate.HasValue ? Model.PreviousEmployer.StartDate.Value.ToString("MM/dd/yyyy") : "" , @class = "form-control datepicker-alt required" })
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <input type="submit" class="btn btn-primary pull-right" value="Let's go!'" />
        </div>

    }
</div>